### ISSUE TITLE
Generate new fill

### ISSUE THREAD

**Issue by serrq** [cyb3rko/pincredible#13]
Sometimes I noticed too much similar numbers close the cells.

Might you add "generate a new filling"?

**Comment by cyb3rko** [comment]
Hmm, didn't think about that yet as it does not have impact on obfuscation.  
Atm that's technically not possible as I just fill an array of integers, so I do not store which one was put in by user and which was filled with randoms.

But that's possible to implement I guess.

**Comment by cyb3rko** [comment]
Implemented in [Version 0.4.1](https://github.com/cyb3rko/pincredible/releases/tag/v0.4.1)

**Comment by cyb3rko** [comment]
Hmm, I don't have an idea for alternative use of the table at the moment.
