### ISSUE TITLE
Colour blind friendly

### ISSUE THREAD

**Issue by venkat2305** [cyb3rko/pincredible#21]
Can you make the patterns friendly for colour blind folks?

**Comment by cyb3rko** [comment]
Good idea, I'll take a look into friendly colors for color blindness.

**Comment by cyb3rko** [comment]
Fyi, the feature is implemented, it will get delivered with the next update.  
The color palette I'm using is the IBM Color Blind Safe Palette.

A showcase including example color blindnesses can be found here:  
https://davidmathlogic.com/colorblind/#%23648FFF-%23785EF0-%23DC267F-%23FE6100-%23FFB000

**Comment by cyb3rko** [comment]
Implemented in [Version 0.6.0](https://github.com/cyb3rko/pincredible/releases/tag/v0.6.0)
