### ISSUE TITLE
Have different frames (coordinates etc.)

### ISSUE THREAD

**Issue by goyalyashpal** [cyb3rko/pincredible#22]
Having different frame options like:
- no frame (current)
- numbered coordinates (suggested default)
- mixed coordinates (like chess)

Additionally:
- puzzle frames (like from games like magic square or the like)

----
Orig8nal description:

Showing coordinates/cell ids on borders (similar to chess board or spreadsheets) by default can additionally help in remembering passwords in case of ...

>  a new pattern for each single PIN ...
> \- @ cyb3rko at https://github.com/cyb3rko/pincredible/issues/16#issuecomment-1452594735

There can be 2 options: 
- Combination (Letters & Numbers)
- Only Numbers

<sup>Oh, and to save your effort :\wink: </sup>

If interested, give it a thumbs up 👍 and write a comment if you want

**Comment by goyalyashpal** [comment]
chess-board-top-view-isolated-on-white-vector-15871268

<img src="https://user-images.githubusercontent.com/19423063/226171972-7cbfb6d9-763b-4149-91f9-12bc948918bc.jpg" width=400px/>

**Comment by goyalyashpal** [comment]
One more frame option can be to look just like a game by using a frame similar to game Sumplete given in #19.

**Comment by cyb3rko** [comment]
The basic coordinates are something i can imagine for the default implementation.
Anything else would most likely as well rather belong to #24.

**Comment by goyalyashpal** [comment]
hi! yes, just the basic coordinates will suffice too;

extremely sorry for even saying this, but can this be hurried a bit 😅😋

**Comment by cyb3rko** [comment]
Sorry, I'm currently pretty busy at work.
Atm the development is rather slow.

**Comment by goyalyashpal** [comment]
ohw, ohkayh. no worries. sorry again...

**Comment by cyb3rko** [comment]
Implemented in [Version 0.6.0](https://github.com/cyb3rko/pincredible/releases/tag/v0.6.0)

**Comment by goyalyashpal** [comment]
hey @ cyb3rko thanks for ssharing update.

the relwase log is _reallyyyy_ nicely categorised: "Breaking Changes, Fixes, Features, Enhancements, Refactorings, Build/Dependencies, CI, Repository, Other, Categorized"

**Comment by cyb3rko** [comment]
@goyalyashpal 
The backup feature, once the app is released, will provide a way to store your PINs somewhere else than directly in your app.  
For example if your phone breaks or the app is cleared, you can recover the PINs from the backup.

Furthermore you can send the backed up PINs to some other device or even other persons.
Until now the backups experienced some breaking changes throughout the update history, in future release versions they (hopefully) won't break.

**Comment by goyalyashpal** [comment]
just to make sure, this won't remove the pin images right?

**Comment by cyb3rko** [comment]
What do you mean it will remove PIN images?  
As stated in the breaking changes, the newest version 0.6.0 won't work saved PINs and backups from older versions as I've switched to a better encryption mode and some other changes.

So once installed you will have to reenter your PINs.
