### ISSUE TITLE
8 by 8 grid to match more with chess board

### ISSUE THREAD

**Issue by goyalyashpal** [cyb3rko/pincredible#23]
Currently it has 7 by 7 grid.

Aim: blend in, & camouflage.

If interested, give it a thumbs up 👍 and write a comment if you want

**Comment by cyb3rko** [comment]
While developing this app I did some experimenting trying to figure out the best pattern size.
I've come up with the current implementation, therefore I would like to stick with the current dimensions for the default pattern.

But extending the size could be made possible through custom patterns in #24 .
