### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [cyb3rko/pincredible#25]
ref: https://github.com/cyb3rko/pincredible/blob/v0.5.0/settings.gradle#L19

ref: https://monitor.f-droid.org/builds/log/com.cyb3rko.pincredible/8#site-footer

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/fc7ec138faaccb1df9a18e09c1cbbbc05902e30a

**Comment by cyb3rko** [comment]
Thanks for the report, haven't recognized it yet.  
I see the problem:

- the underlying library was moved to https://github.com/cyb3rko/backpack-apps for usage in multiple apps
- the GitHub pipeline for automatically building and uploading the apk file does work by cloning the remote library repo to be able to build it
- the F-Droid build does not have this custom logic to rely on the remote library repo, any way to include this into the build?

**Comment by licaon-kter** [comment]
> the F-Droid build does not have this custom logic to rely on the remote library repo, any way to include this into the build?

The remote is `../somepath/` ? How does that work out for you exactly when you clone this project in a random folder?

Wanna use that? Use a submodule: https://git-scm.com/book/en/v2/Git-Tools-Submodules :)

**Comment by cyb3rko** [comment]
Atm it works by cloning the library in the same parent folder... Yeah, a bit of a workaround, but I just wanted it to work for now as I had no time to investigate further how to do that properly.

Maybe it's time now to take a look at submodules, good call. Would that would well with the F-Droid build then?

**Comment by licaon-kter** [comment]
Yes, as the submodules will get cloned too, then you can reference them at will.

**Comment by cyb3rko** [comment]
@licaon-kter I have included the submodule now and adapted the build scripts for the release apk output.
It seems to work on my site now, let's see if that works on your side (F-Droid build) as well.

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/commit/b789edbb6ff92f40b54f8915390907261497f994
