### ISSUE TITLE
Squares change height when dpi is not default

### ISSUE THREAD

**Issue by Murilogs1910** [cyb3rko/pincredible#29]
If I decrease the dpi, their height also decreases, if I increase it, their height also increase. They should stay as squares.

<details><p align='center'>
<summary>Screenshots (middle one is with default dpi)</summary>

<img width=30% src='https://i.postimg.cc/pThDrXFg/zbnhlzx36ob8cct8.jpg'><img width=30% src='https://i.postimg.cc/g2yrtKkr/0i17ncd8blz90lpa.jpg'><img width=30% src='https://i.postimg.cc/9Ffnpyy2/0st0hbefzkvzexoq.jpg'>
</p></details>

**Comment by cyb3rko** [comment]
Yep, has been on my to-do list for a while now, especially because on bigger screens like foldables or tablets it looks a bit off.  
Thank you

**Comment by cyb3rko** [comment]
Should be corrected in [Version 0.7.1](https://github.com/cyb3rko/pincredible/releases/tag/v0.7.1).  
Can you double check?
